export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  z
  fzf
  fzf-tab
  zsh-completions
)

source $ZSH/oh-my-zsh.sh

# fzf-tab: show folder contents preview when tabbing through directories
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza --color=always --icons $realpath'
zstyle ':fzf-tab:complete:z:*' fzf-preview 'eza --color=always --icons $realpath'

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"
export PATH="$PATH:$(go env GOPATH)/bin"

source ~/.dotfiles/zsh/aliases
source ~/.dotfiles/zsh/functions

if [[ "$OSTYPE" == "darwin"* ]]; then
  source ~/.dotfiles/zsh/aliases.mac
else
  source ~/.dotfiles/zsh/aliases.linux
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

[ -f ~/.zshrc.local ] && source ~/.zshrc.local
eval "$(starship init zsh)"
